### ISSUE TITLE
Move sequence and logic parts of SCD to IEC 61131-10 encoding

### ISSUE THREAD

**Issue by AlexTxen** [equinor/iec63131#13]
Proposal given in #12 should be evaluated and decision shall be taken by Committee.

This is huge change to current approach, which was decided and justified previously.
Current work on AML library will be still continued in existing way until decision will be taken.

**Comment by Erik0x42** [comment]
What is the reason for closing this issue?

I don't recall that this proposal has been discussed all the way to a conclusion.

I would suggest a splitting of this into two issues, one for sequence designs in IEC 61131-10 format and one for SCD designs in IEC 61131-10 format, so that they may be discussed and concluded separately.
